
version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "/mono" 
    schedule:
      interval: "daily"
      
  - package-ecosystem: "npm"
    directory: "/client" 
    schedule:
      interval: "daily"
