
version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "/mono"
    target-branch: "master"
    schedule:
      interval: "daily"
      
      
  - package-ecosystem: "npm"
    directory: "/client" 
    target-branch: "master"
    schedule:
      interval: "daily"
      
