import config from './config.js';

const { limits } = config;

export const ROOM_CODE_PATTERN = /^[A-Z0-9]{4}-[A-Z0-9]{4}-[A-Z0-9]{4}$/;

/**
 * Every value crossing the socket boundary is attacker-controlled. Socket.IO
 * will happily deliver `null`, a number, or a 40 MB string to a handler that
 * assumed a short string — so nothing in this file trusts its input, and every
 * handler in signaling.js runs its payload through here first.
 */

export class ValidationError extends Error {
  constructor(message, code = 'INVALID_PAYLOAD') {
    super(message);
    this.name = 'ValidationError';
    this.code = code;
  }
}

/** All C0/C1 control characters. */
const CONTROL_CHARS = /[\u0000-\u001F\u007F-\u009F]/g;
/** Same, but sparing tab and newline, which chat legitimately contains. */
const CONTROL_CHARS_KEEP_BREAKS = /[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F-\u009F]/g;
/** Bidi overrides and zero-width joiners used to spoof display names. */
const INVISIBLE_CHARS = /[\u200B-\u200F\u2028-\u202E\u2066-\u2069\uFEFF]/g;

/** Strips control characters and collapses runs of whitespace. */
export function cleanText(value, { max, field }) {
  if (typeof value !== 'string') {
    throw new ValidationError(`${field} must be text.`);
  }

  // Control characters become spaces rather than vanishing, so "a<NUL>b"
  // cannot be smuggled through as the visually distinct name "ab".
  const collapsed = value
    .replace(CONTROL_CHARS, ' ')
    .replace(INVISIBLE_CHARS, '')
    .replace(/\s+/g, ' ')
    .trim();

  if (!collapsed) throw new ValidationError(`${field} cannot be empty.`);
  if (collapsed.length > max) {
    throw new ValidationError(`${field} must be ${max} characters or fewer.`);
  }
  return collapsed;
}

/** Chat bodies keep their newlines; only hard control chars are removed. */
export function cleanMessageBody(value) {
  if (typeof value !== 'string') {
    throw new ValidationError('Message must be text.');
  }

  const trimmed = value
    .replace(CONTROL_CHARS_KEEP_BREAKS, '')
    .replace(INVISIBLE_CHARS, '')
    .replace(/[ \t]+$/gm, '')
    // Collapse runaway newline padding used to blow out other people's UI.
    .replace(/\n{4,}/g, '\n\n\n')
    .trim();

  if (!trimmed) throw new ValidationError('Message cannot be empty.');
  if (trimmed.length > limits.maxMessageLength) {
    throw new ValidationError(
      `Message must be ${limits.maxMessageLength} characters or fewer.`
    );
  }
  return trimmed;
}

export function cleanDisplayName(value) {
  return cleanText(value, {
    max: limits.maxDisplayNameLength,
    field: 'Display name',
  });
}

export function cleanRoomName(value) {
  return cleanText(value, {
    max: limits.maxRoomNameLength,
    field: 'Room name',
  });
}

export function cleanRoomCode(value) {
  if (typeof value !== 'string') {
    throw new ValidationError('Room code must be text.', 'BAD_ROOM_CODE');
  }
  const normalized = value.trim().toUpperCase();
  if (!ROOM_CODE_PATTERN.test(normalized)) {
    throw new ValidationError(
      'Room codes look like ABCD-1234-EFGH.',
      'BAD_ROOM_CODE'
    );
  }
  return normalized;
}

/**
 * Socket IDs are generated by Socket.IO and are URL-safe base64ish, ~20 chars.
 * Bounding the shape stops a client from using this field as a payload smuggler.
 */
export function cleanSocketId(value, field = 'Peer id') {
  if (typeof value !== 'string' || !/^[A-Za-z0-9_-]{1,64}$/.test(value)) {
    throw new ValidationError(`${field} is not a valid peer id.`);
  }
  return value;
}

export function cleanBoolean(value, fallback = false) {
  if (typeof value === 'boolean') return value;
  if (value == null) return fallback;
  return Boolean(value);
}

export function cleanObject(value, field = 'Payload') {
  if (value === null || typeof value !== 'object' || Array.isArray(value)) {
    throw new ValidationError(`${field} must be an object.`);
  }
  return value;
}

/**
 * SDP and ICE candidates are opaque to us — we relay them without inspecting
 * their contents. What we *do* enforce is shape and size, so a peer cannot use
 * the signaling channel as an unmetered message bus or a memory-exhaustion
 * vector against other clients.
 */
const MAX_SDP_BYTES = 128 * 1024;
const MAX_CANDIDATE_BYTES = 4 * 1024;

export function cleanSessionDescription(value) {
  const sdp = cleanObject(value, 'Session description');

  if (sdp.type !== 'offer' && sdp.type !== 'answer') {
    throw new ValidationError('Session description type must be offer/answer.');
  }
  if (typeof sdp.sdp !== 'string' || !sdp.sdp) {
    throw new ValidationError('Session description is missing its SDP body.');
  }
  if (sdp.sdp.length > MAX_SDP_BYTES) {
    throw new ValidationError('Session description is too large.');
  }

  // Reconstructed rather than passed through, so no extra attacker-chosen
  // properties ride along to the receiving peer.
  return { type: sdp.type, sdp: sdp.sdp };
}

export function cleanIceCandidate(value) {
  const candidate = cleanObject(value, 'ICE candidate');

  if (typeof candidate.candidate !== 'string') {
    throw new ValidationError('ICE candidate is malformed.');
  }
  if (candidate.candidate.length > MAX_CANDIDATE_BYTES) {
    throw new ValidationError('ICE candidate is too large.');
  }

  const index = candidate.sdpMLineIndex;
  if (index != null && (!Number.isInteger(index) || index < 0 || index > 128)) {
    throw new ValidationError('ICE candidate index is out of range.');
  }

  const mid = candidate.sdpMid;
  if (mid != null && (typeof mid !== 'string' || mid.length > 64)) {
    throw new ValidationError('ICE candidate mid is malformed.');
  }

  return {
    candidate: candidate.candidate,
    sdpMLineIndex: index ?? null,
    sdpMid: mid ?? null,
    usernameFragment:
      typeof candidate.usernameFragment === 'string' &&
      candidate.usernameFragment.length <= 256
        ? candidate.usernameFragment
        : null,
  };
}

/** Presence flags a peer advertises about itself (mic/cam/screen state). */
export function cleanPeerState(value) {
  const state = cleanObject(value, 'Peer state');
  return {
    audio: cleanBoolean(state.audio, true),
    video: cleanBoolean(state.video, true),
    screen: cleanBoolean(state.screen, false),
    handRaised: cleanBoolean(state.handRaised, false),
  };
}
